
name: Build Android APK
on: [push, pull_request] # سيتم البناء تلقائياً عند رفع أي كود جديد

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSashko/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
